### PR TITLE
fix: Handle changing href for `<Link />` correctly when using `localePrefix: 'never'`

### LINKED ISSUE #918: Link `href` doesn't update when search params change when `localePrefix` is set to `never`.
### Description

If a `Link` is present in a client component and the url depends on the existing `searchParams`, the url is not updated when the `searchParams` change. For some reason this happens when `createSharedPathnamesNavigation` is invoked with `localePrefix: "never"`, default value seems to work fine.

### Mandatory reproduction URL

https://codesandbox.io/p/github/jorgemoya/next-intl-bug-repro-app-router/main?import=true

### Reproduction description

Steps to reproduce:
1. Open reproduction
2. Click on `Foo` link
3. Hover over `Broken Link` and notice it doesn't include `foo=bar` search params when it should.

Alternate:
1. Open reproduction
2. Click on `Foo` link
3. Refresh page
4. Click on `Home` link
5. Hover over `Broken Link` and notice it does include `foo=bar` search params when it shouldn't.

### Expected behaviour

The expected behavior would be for the `Broken Link` link the match the search params present, even after they update.

### PR DESCRIPTION
**Pull request by amannn**
Fixes #918

### CODE REVIEW

File: packages/next-intl/src/navigation/shared/BaseLink.tsx [hunk 1]
```diff
@@ -52,12 +52,12 @@ function BaseLink(
...
 
   useEffect(() => {
-    if (!pathname || localePrefix === 'never') return;
+    if (!pathname) return;
 
     setLocalizedHref(
       localizeHref(href, locale, defaultLocale, pathname ?? undefined)
     );
-  }, [defaultLocale, href, locale, localePrefix, pathname]);
+  }, [defaultLocale, href, locale, pathname]);
```
Comment (amannn) [inline packages/next-intl/src/navigation/shared/BaseLink.tsx:60]: Why do we need this effect in the first place? Is this outdated and can we remove it?

Comment (amannn) [reply packages/next-intl/src/navigation/shared/BaseLink.tsx]: Added some notes to https://github.com/amannn/next-intl/issues/444#issue-1839328048, let's continue there …
